name: rtfi_client_web
description: "Client side application for visualizing real-time flight data from an sse source"
publish_to: 'none' #DO NOT REMOVE
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1
  syncfusion_flutter_charts: ^24.2.7+1
  syncfusion_flutter_maps: ^24.2.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  meta: ^1.11.0
  logging: ^1.2.0
  http: ^1.2.1
  side_sheet: ^1.0.4
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/custom.geo.json
